services:
  my-server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      my-cache-server:
        condition: service_healthy
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD","redis-cli","ping" ]
      interval: 5s
      retries: 10
