name: Deploy To EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create application.yml file
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application-dev.yml

      - name: Build the project
        run: ./gradlew clean build

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag Docker image
        run: |
          docker build -t extra-server .
          docker tag extra-server:latest 992382625968.dkr.ecr.ap-northeast-2.amazonaws.com/extra-server:latest

      - name: Push Docker image to ECR
        run: docker push 992382625968.dkr.ecr.ap-northeast-2.amazonaws.com/extra-server:latest

      - name: Deploy to EC2 via SSH and update services
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            script_stop: true
            script: |
              cd ~/extra-server
              docker-compose down
              docker-compose pull
              docker-compose up -d
      - name: Remove unused Docker images
        run: |
          docker image prune -af --filter "until=24h"
