name: Deploy To EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create application.yml file
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application-dev.yml

      - name: Build the project
        run: ./gradlew clean build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images using Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: Push Docker images to ECR
        run: |
          IMAGE_NAME=${{ steps.login-ecr.outputs.registry }}/extra-server
          docker tag extra-server:latest $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker-compose down
            docker-compose pull
            docker-compose up -d
